# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/phxlk/Workspace/Computing/Saffron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/phxlk/Workspace/Computing/Saffron

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phxlk/Workspace/Computing/Saffron/CMakeFiles /home/phxlk/Workspace/Computing/Saffron/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/phxlk/Workspace/Computing/Saffron/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Saffron_test

# Build rule for target.
Saffron_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Saffron_test
.PHONY : Saffron_test

# fast build rule for target.
Saffron_test/fast:
	$(MAKE) -f CMakeFiles/Saffron_test.dir/build.make CMakeFiles/Saffron_test.dir/build
.PHONY : Saffron_test/fast

#=============================================================================
# Target rules for targets named saffron

# Build rule for target.
saffron: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 saffron
.PHONY : saffron

# fast build rule for target.
saffron/fast:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/build
.PHONY : saffron/fast

Saffron.o: Saffron.cpp.o
.PHONY : Saffron.o

# target to build an object file
Saffron.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/Saffron.cpp.o
.PHONY : Saffron.cpp.o

Saffron.i: Saffron.cpp.i
.PHONY : Saffron.i

# target to preprocess a source file
Saffron.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/Saffron.cpp.i
.PHONY : Saffron.cpp.i

Saffron.s: Saffron.cpp.s
.PHONY : Saffron.s

# target to generate assembly for a file
Saffron.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/Saffron.cpp.s
.PHONY : Saffron.cpp.s

src/SafAlgorithm.o: src/SafAlgorithm.cpp.o
.PHONY : src/SafAlgorithm.o

# target to build an object file
src/SafAlgorithm.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafAlgorithm.cpp.o
.PHONY : src/SafAlgorithm.cpp.o

src/SafAlgorithm.i: src/SafAlgorithm.cpp.i
.PHONY : src/SafAlgorithm.i

# target to preprocess a source file
src/SafAlgorithm.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafAlgorithm.cpp.i
.PHONY : src/SafAlgorithm.cpp.i

src/SafAlgorithm.s: src/SafAlgorithm.cpp.s
.PHONY : src/SafAlgorithm.s

# target to generate assembly for a file
src/SafAlgorithm.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafAlgorithm.cpp.s
.PHONY : src/SafAlgorithm.cpp.s

src/SafCoincidenceFinder.o: src/SafCoincidenceFinder.cpp.o
.PHONY : src/SafCoincidenceFinder.o

# target to build an object file
src/SafCoincidenceFinder.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafCoincidenceFinder.cpp.o
.PHONY : src/SafCoincidenceFinder.cpp.o

src/SafCoincidenceFinder.i: src/SafCoincidenceFinder.cpp.i
.PHONY : src/SafCoincidenceFinder.i

# target to preprocess a source file
src/SafCoincidenceFinder.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafCoincidenceFinder.cpp.i
.PHONY : src/SafCoincidenceFinder.cpp.i

src/SafCoincidenceFinder.s: src/SafCoincidenceFinder.cpp.s
.PHONY : src/SafCoincidenceFinder.s

# target to generate assembly for a file
src/SafCoincidenceFinder.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafCoincidenceFinder.cpp.s
.PHONY : src/SafCoincidenceFinder.cpp.s

src/SafDataSet.o: src/SafDataSet.cpp.o
.PHONY : src/SafDataSet.o

# target to build an object file
src/SafDataSet.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafDataSet.cpp.o
.PHONY : src/SafDataSet.cpp.o

src/SafDataSet.i: src/SafDataSet.cpp.i
.PHONY : src/SafDataSet.i

# target to preprocess a source file
src/SafDataSet.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafDataSet.cpp.i
.PHONY : src/SafDataSet.cpp.i

src/SafDataSet.s: src/SafDataSet.cpp.s
.PHONY : src/SafDataSet.s

# target to generate assembly for a file
src/SafDataSet.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafDataSet.cpp.s
.PHONY : src/SafDataSet.cpp.s

src/SafEventBuilder.o: src/SafEventBuilder.cpp.o
.PHONY : src/SafEventBuilder.o

# target to build an object file
src/SafEventBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafEventBuilder.cpp.o
.PHONY : src/SafEventBuilder.cpp.o

src/SafEventBuilder.i: src/SafEventBuilder.cpp.i
.PHONY : src/SafEventBuilder.i

# target to preprocess a source file
src/SafEventBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafEventBuilder.cpp.i
.PHONY : src/SafEventBuilder.cpp.i

src/SafEventBuilder.s: src/SafEventBuilder.cpp.s
.PHONY : src/SafEventBuilder.s

# target to generate assembly for a file
src/SafEventBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafEventBuilder.cpp.s
.PHONY : src/SafEventBuilder.cpp.s

src/SafFilter.o: src/SafFilter.cpp.o
.PHONY : src/SafFilter.o

# target to build an object file
src/SafFilter.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafFilter.cpp.o
.PHONY : src/SafFilter.cpp.o

src/SafFilter.i: src/SafFilter.cpp.i
.PHONY : src/SafFilter.i

# target to preprocess a source file
src/SafFilter.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafFilter.cpp.i
.PHONY : src/SafFilter.cpp.i

src/SafFilter.s: src/SafFilter.cpp.s
.PHONY : src/SafFilter.s

# target to generate assembly for a file
src/SafFilter.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafFilter.cpp.s
.PHONY : src/SafFilter.cpp.s

src/SafGeometry.o: src/SafGeometry.cpp.o
.PHONY : src/SafGeometry.o

# target to build an object file
src/SafGeometry.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafGeometry.cpp.o
.PHONY : src/SafGeometry.cpp.o

src/SafGeometry.i: src/SafGeometry.cpp.i
.PHONY : src/SafGeometry.i

# target to preprocess a source file
src/SafGeometry.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafGeometry.cpp.i
.PHONY : src/SafGeometry.cpp.i

src/SafGeometry.s: src/SafGeometry.cpp.s
.PHONY : src/SafGeometry.s

# target to generate assembly for a file
src/SafGeometry.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafGeometry.cpp.s
.PHONY : src/SafGeometry.cpp.s

src/SafPeakFitter.o: src/SafPeakFitter.cpp.o
.PHONY : src/SafPeakFitter.o

# target to build an object file
src/SafPeakFitter.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafPeakFitter.cpp.o
.PHONY : src/SafPeakFitter.cpp.o

src/SafPeakFitter.i: src/SafPeakFitter.cpp.i
.PHONY : src/SafPeakFitter.i

# target to preprocess a source file
src/SafPeakFitter.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafPeakFitter.cpp.i
.PHONY : src/SafPeakFitter.cpp.i

src/SafPeakFitter.s: src/SafPeakFitter.cpp.s
.PHONY : src/SafPeakFitter.s

# target to generate assembly for a file
src/SafPeakFitter.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafPeakFitter.cpp.s
.PHONY : src/SafPeakFitter.cpp.s

src/SafRawDataChannel.o: src/SafRawDataChannel.cpp.o
.PHONY : src/SafRawDataChannel.o

# target to build an object file
src/SafRawDataChannel.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataChannel.cpp.o
.PHONY : src/SafRawDataChannel.cpp.o

src/SafRawDataChannel.i: src/SafRawDataChannel.cpp.i
.PHONY : src/SafRawDataChannel.i

# target to preprocess a source file
src/SafRawDataChannel.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataChannel.cpp.i
.PHONY : src/SafRawDataChannel.cpp.i

src/SafRawDataChannel.s: src/SafRawDataChannel.cpp.s
.PHONY : src/SafRawDataChannel.s

# target to generate assembly for a file
src/SafRawDataChannel.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataChannel.cpp.s
.PHONY : src/SafRawDataChannel.cpp.s

src/SafRawDataSet.o: src/SafRawDataSet.cpp.o
.PHONY : src/SafRawDataSet.o

# target to build an object file
src/SafRawDataSet.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataSet.cpp.o
.PHONY : src/SafRawDataSet.cpp.o

src/SafRawDataSet.i: src/SafRawDataSet.cpp.i
.PHONY : src/SafRawDataSet.i

# target to preprocess a source file
src/SafRawDataSet.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataSet.cpp.i
.PHONY : src/SafRawDataSet.cpp.i

src/SafRawDataSet.s: src/SafRawDataSet.cpp.s
.PHONY : src/SafRawDataSet.s

# target to generate assembly for a file
src/SafRawDataSet.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawDataSet.cpp.s
.PHONY : src/SafRawDataSet.cpp.s

src/SafRawPlots.o: src/SafRawPlots.cpp.o
.PHONY : src/SafRawPlots.o

# target to build an object file
src/SafRawPlots.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawPlots.cpp.o
.PHONY : src/SafRawPlots.cpp.o

src/SafRawPlots.i: src/SafRawPlots.cpp.i
.PHONY : src/SafRawPlots.i

# target to preprocess a source file
src/SafRawPlots.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawPlots.cpp.i
.PHONY : src/SafRawPlots.cpp.i

src/SafRawPlots.s: src/SafRawPlots.cpp.s
.PHONY : src/SafRawPlots.s

# target to generate assembly for a file
src/SafRawPlots.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRawPlots.cpp.s
.PHONY : src/SafRawPlots.cpp.s

src/SafRunner.o: src/SafRunner.cpp.o
.PHONY : src/SafRunner.o

# target to build an object file
src/SafRunner.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRunner.cpp.o
.PHONY : src/SafRunner.cpp.o

src/SafRunner.i: src/SafRunner.cpp.i
.PHONY : src/SafRunner.i

# target to preprocess a source file
src/SafRunner.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRunner.cpp.i
.PHONY : src/SafRunner.cpp.i

src/SafRunner.s: src/SafRunner.cpp.s
.PHONY : src/SafRunner.s

# target to generate assembly for a file
src/SafRunner.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafRunner.cpp.s
.PHONY : src/SafRunner.cpp.s

src/SafTrigger.o: src/SafTrigger.cpp.o
.PHONY : src/SafTrigger.o

# target to build an object file
src/SafTrigger.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTrigger.cpp.o
.PHONY : src/SafTrigger.cpp.o

src/SafTrigger.i: src/SafTrigger.cpp.i
.PHONY : src/SafTrigger.i

# target to preprocess a source file
src/SafTrigger.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTrigger.cpp.i
.PHONY : src/SafTrigger.cpp.i

src/SafTrigger.s: src/SafTrigger.cpp.s
.PHONY : src/SafTrigger.s

# target to generate assembly for a file
src/SafTrigger.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTrigger.cpp.s
.PHONY : src/SafTrigger.cpp.s

src/SafTriggerDataSet.o: src/SafTriggerDataSet.cpp.o
.PHONY : src/SafTriggerDataSet.o

# target to build an object file
src/SafTriggerDataSet.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerDataSet.cpp.o
.PHONY : src/SafTriggerDataSet.cpp.o

src/SafTriggerDataSet.i: src/SafTriggerDataSet.cpp.i
.PHONY : src/SafTriggerDataSet.i

# target to preprocess a source file
src/SafTriggerDataSet.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerDataSet.cpp.i
.PHONY : src/SafTriggerDataSet.cpp.i

src/SafTriggerDataSet.s: src/SafTriggerDataSet.cpp.s
.PHONY : src/SafTriggerDataSet.s

# target to generate assembly for a file
src/SafTriggerDataSet.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerDataSet.cpp.s
.PHONY : src/SafTriggerDataSet.cpp.s

src/SafTriggerPlots.o: src/SafTriggerPlots.cpp.o
.PHONY : src/SafTriggerPlots.o

# target to build an object file
src/SafTriggerPlots.cpp.o:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerPlots.cpp.o
.PHONY : src/SafTriggerPlots.cpp.o

src/SafTriggerPlots.i: src/SafTriggerPlots.cpp.i
.PHONY : src/SafTriggerPlots.i

# target to preprocess a source file
src/SafTriggerPlots.cpp.i:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerPlots.cpp.i
.PHONY : src/SafTriggerPlots.cpp.i

src/SafTriggerPlots.s: src/SafTriggerPlots.cpp.s
.PHONY : src/SafTriggerPlots.s

# target to generate assembly for a file
src/SafTriggerPlots.cpp.s:
	$(MAKE) -f CMakeFiles/saffron.dir/build.make CMakeFiles/saffron.dir/src/SafTriggerPlots.cpp.s
.PHONY : src/SafTriggerPlots.cpp.s

test/simpletest.o: test/simpletest.cpp.o
.PHONY : test/simpletest.o

# target to build an object file
test/simpletest.cpp.o:
	$(MAKE) -f CMakeFiles/Saffron_test.dir/build.make CMakeFiles/Saffron_test.dir/test/simpletest.cpp.o
.PHONY : test/simpletest.cpp.o

test/simpletest.i: test/simpletest.cpp.i
.PHONY : test/simpletest.i

# target to preprocess a source file
test/simpletest.cpp.i:
	$(MAKE) -f CMakeFiles/Saffron_test.dir/build.make CMakeFiles/Saffron_test.dir/test/simpletest.cpp.i
.PHONY : test/simpletest.cpp.i

test/simpletest.s: test/simpletest.cpp.s
.PHONY : test/simpletest.s

# target to generate assembly for a file
test/simpletest.cpp.s:
	$(MAKE) -f CMakeFiles/Saffron_test.dir/build.make CMakeFiles/Saffron_test.dir/test/simpletest.cpp.s
.PHONY : test/simpletest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Saffron_test"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... saffron"
	@echo "... test"
	@echo "... Saffron.o"
	@echo "... Saffron.i"
	@echo "... Saffron.s"
	@echo "... src/SafAlgorithm.o"
	@echo "... src/SafAlgorithm.i"
	@echo "... src/SafAlgorithm.s"
	@echo "... src/SafCoincidenceFinder.o"
	@echo "... src/SafCoincidenceFinder.i"
	@echo "... src/SafCoincidenceFinder.s"
	@echo "... src/SafDataSet.o"
	@echo "... src/SafDataSet.i"
	@echo "... src/SafDataSet.s"
	@echo "... src/SafEventBuilder.o"
	@echo "... src/SafEventBuilder.i"
	@echo "... src/SafEventBuilder.s"
	@echo "... src/SafFilter.o"
	@echo "... src/SafFilter.i"
	@echo "... src/SafFilter.s"
	@echo "... src/SafGeometry.o"
	@echo "... src/SafGeometry.i"
	@echo "... src/SafGeometry.s"
	@echo "... src/SafPeakFitter.o"
	@echo "... src/SafPeakFitter.i"
	@echo "... src/SafPeakFitter.s"
	@echo "... src/SafRawDataChannel.o"
	@echo "... src/SafRawDataChannel.i"
	@echo "... src/SafRawDataChannel.s"
	@echo "... src/SafRawDataSet.o"
	@echo "... src/SafRawDataSet.i"
	@echo "... src/SafRawDataSet.s"
	@echo "... src/SafRawPlots.o"
	@echo "... src/SafRawPlots.i"
	@echo "... src/SafRawPlots.s"
	@echo "... src/SafRunner.o"
	@echo "... src/SafRunner.i"
	@echo "... src/SafRunner.s"
	@echo "... src/SafTrigger.o"
	@echo "... src/SafTrigger.i"
	@echo "... src/SafTrigger.s"
	@echo "... src/SafTriggerDataSet.o"
	@echo "... src/SafTriggerDataSet.i"
	@echo "... src/SafTriggerDataSet.s"
	@echo "... src/SafTriggerPlots.o"
	@echo "... src/SafTriggerPlots.i"
	@echo "... src/SafTriggerPlots.s"
	@echo "... test/simpletest.o"
	@echo "... test/simpletest.i"
	@echo "... test/simpletest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

